In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import pytz
from datetime import datetime

import matplotlib.pyplot as plt

%matplotlib qt

In [2]:
# Read csv file into a pandas dataframe
ci_df = pd.read_csv("dailycheckins.csv")
ci_df

           user                       timestamp  hours               project
0           ned         2019-09-27 00:00:00 UTC   8.00                bizdev
1        robert             09/27/2019 12:00 AM   8.00                bizdev
2           ned          26 сентября 2019 00:00   4.00                bizdev
3           ned         2019-09-26 00:00:00 UTC   1.00  cultureandmanagement
4           ned         2019-09-26 00:00:00 UTC   1.50            project-00
5           ned         2019-09-26 00:00:00 UTC   1.00            project-43
6         jaime             12/21/2018 12:00 AM   2.00            project-00
7         jaime         2018-12-21 00:00:00 UTC   0.50            project-47
8         jaime         2018-12-21 00:00:00 UTC   3.50            project-47
9         jaime         2018-12-20 00:00:00 UTC   1.50            project-00
10        jaime         2018-12-20 00:00:00 UTC   1.50            project-30
11        jaime         2018-12-20 00:00:00 UTC   1.00            project-47
12        jaime         2018-12-20 00:00:00 UTC   3.00            project-47
13      catelyn    2018-11-26 14:47:36.0429 UTC   0.60           opsandadmin
14      catelyn    2018-11-26 14:47:36.0429 UTC   0.45           opsandadmin
15      catelyn    2018-11-26 14:47:36.0429 UTC   0.40  cultureandmanagement
16      catelyn    2018-11-26 14:47:36.0429 UTC   0.08              security
17      catelyn    2018-11-26 14:47:36.0429 UTC   0.68            project-43
18      catelyn    2018-11-26 14:47:36.0429 UTC   0.35           opsandadmin
19      catelyn    2018-11-26 14:47:36.0429 UTC   1.53            project-43
20      catelyn            26 ноября 2018 14:47   0.72           opsandadmin
21      catelyn    2018-11-26 14:47:36.0429 UTC   0.38  cultureandmanagement
22      catelyn    2018-11-26 14:47:36.0429 UTC   0.62  cultureandmanagement
23       cersei    2018-11-26 13:17:30.0426 UTC   3.00             blogideas
24       cersei    2018-11-26 13:17:30.0426 UTC   1.00            project-10
25       cersei    2018-11-26 13:17:30.0426 UTC   4.00              internal
26     daenerys    2018-11-26 12:55:30.0416 UTC   8.00             blogideas
27     daenerys    2018-11-26 12:55:30.0416 UTC   0.50            project-51
28        jorah             11/26/2018 12:49 PM   2.00            project-51
29        jorah    2018-11-26 12:49:17.0405 UTC   1.50               transit
...         ...                             ...    ...                   ...
20470     jorah    2017-06-20 07:57:21.1777 UTC   0.50            project-60
20471     jorah  2017-06-19 09:07:51.085966 UTC   1.50           opsandadmin
20472     jorah  2017-06-19 09:07:51.085966 UTC   0.50           opsandadmin
20473     jorah  2017-06-19 09:07:51.085966 UTC   1.50             workshops
20474     jorah  2017-06-19 09:07:51.085966 UTC   0.50             workshops
20475     jorah  2017-06-19 09:07:51.085966 UTC   0.50            project-65
20476     jorah  2017-06-19 09:07:51.085966 UTC   0.50            project-65
20477  margaery         2017-04-20 00:00:00 UTC   5.00            project-30
20478  margaery         2017-04-20 00:00:00 UTC   2.00              learning
20479  margaery         2017-04-20 00:00:00 UTC   3.50            project-30
20480  margaery         2017-04-20 00:00:00 UTC   1.50            project-68
20481  margaery         2017-04-04 00:00:00 UTC   3.00  cultureandmanagement
20482  margaery         2017-04-04 00:00:00 UTC   7.00                bizdev
20483    robert         2016-06-13 00:00:00 UTC   3.50            project-20
20484    robert         2016-06-13 00:00:00 UTC   2.00                bizdev
20485    robert             06/13/2016 12:00 AM   0.50           opsandadmin
20486    robert         2016-06-13 00:00:00 UTC   2.00               transit
20487    robert         2010-10-04 00:00:00 UTC   1.00           opsandadmin
20488    robert         2010-10-04 00:00:00 UTC   1.50            project-30
20489    robert         2010-10-04 00:00:00 UTC   1.50               transit
20490    robert         2010-10-04 00:00:00 UTC   1.50                bizdev
20491    robert         2010-10-04 00:00:00 UTC   2.00                bizdev
20492    robert         2010-10-04 00:00:00 UTC   0.50                bizdev
20493    robert         2010-10-04 00:00:00 UTC   2.00           opsandadmin
20494    robert         2010-10-04 00:00:00 UTC   2.00            project-64
20495    robert         2010-10-04 00:00:00 UTC   2.00               transit
20496    robert         2010-10-04 00:00:00 UTC   2.00  cultureandmanagement
20497    robert            4 октября 2010 00:00   1.50                bizdev
20498    robert         2010-10-04 00:00:00 UTC   1.00               transit
20499    robert         2010-10-04 00:00:00 UTC   6.00                bizdev

[20500 rows x 4 columns]

In [3]:
# Knowing which rows have null values
ci_df[ci_df['user'].isna()]

      user                       timestamp  hours     project
15797  NaN  2017-12-27 10:36:14.000121 UTC   4.00  project-40
15798  NaN  2017-12-27 10:36:14.000121 UTC   3.00    learning
17572  NaN  2017-10-12 10:31:44.000227 UTC   2.75  project-47
17573  NaN  2017-10-12 10:31:44.000227 UTC   4.00      bizdev
17574  NaN  2017-10-12 10:31:44.000227 UTC   1.00     transit

In [4]:
ci_df.project.unique()

array(['bizdev', 'cultureandmanagement', 'project-00', 'project-43',
       'project-47', 'project-30', 'opsandadmin', 'security', 'blogideas',
       'project-10', 'internal', 'project-51', 'transit', 'learning',
       'products', 'project-64', 'project-26', 'project-66', 'events',
       'project-25', 'project-32', 'project-31', 'finance', 'project-40',
       'engineering', 'project-09', 'project-65', 'project-28',
       'project-27', 'website', 'marketing', 'blog-ideas', 'hiring',
       'project-46', 'project-06', 'pm', 'project-07', 'legal',
       'project-33', 'strategy', 'project-05', 'project-62',
       'datastrategy', 'project-22', 'project-70', 'project-69',
       'project-04', 'opdandadmin', 'project-38', 'internals', 'leave',
       'recruitment', 'clutureandmanagement', 'project-01',
       'datastorytelling', 'project-08', 'project-19', 'project-73',
       'lunch', 'sqool', 'project-20', 'onboarding', 'workshops',
       'project-36', 'data', 'machine-learning', 'weeklygoals', 'qgis',
       'project-49', 'pandas', 'culturandmanagement', 'project-59',
       'brief', 'opandadmin', 'cultureandmanagemen', 'project-68',
       'project-57', 'project-58', 'project-16', 'media', 'new-office',
       'd3js', 'workshop', 'misc', 'random', 'project-13', 'project-29',
       'design', 'machinelearning', 'project-55', 'project-11',
       'project-44', 'project-56', 'project-41', 'dogood', 'project-02',
       'braintooling', 'dataethics', 'project-42', 'opssandadmin',
       'project-67', 'debugging', 'branding', 'project-34', 'project-18',
       'project-45', 'miscellaneous', 'project-39', 'project-21',
       'project-54', 'project-48', 'opsandamin', 'laptop', 'project-17',
       'cultureandmangement', 'project-24', 'project-23', 'blogpost',
       'project-14', 'project-03', 'traffic', 'airflow', 'project-72',
       'project-37', 'breakout', 'project-71', 'project-53',
       'fatnesscheckin', 'project-52', 'project-35', 'project-74',
       'hirng', 'overthinking', 'project-61', 'project-50', 'project-12',
       'opsandandmin', 'opsadadmin', 'interns', 'project-63',
       'friendship', 'project-15', 'paperwork', 'project-60'],
      dtype=object)

In [5]:
ci_df.project.value_counts()

opsandadmin             2824
bizdev                  1784
cultureandmanagement    1273
learning                1179
project-00               946
project-10               672
website                  639
project-40               612
blogideas                567
project-43               526
project-68               485
project-64               484
project-25               467
project-65               465
project-20               456
hiring                   446
project-13               385
project-06               329
project-55               321
project-73               310
transit                  293
workshops                285
engineering              271
project-30               268
project-16               246
project-47               225
events                   219
project-51               215
project-27               206
project-32               200
                        ...
dogood                     1
opandadmin                 1
project-60                 1
overthinking               1
traffic                    1
fatnesscheckin             1
weeklygoals                1
friendship                 1
miscellaneous              1
hirng                      1
opsadadmin                 1
laptop                     1
project-21                 1
project-15                 1
cultureandmanagemen        1
paperwork                  1
project-02                 1
project-61                 1
project-39                 1
project-41                 1
dataethics                 1
opsandandmin               1
project-12                 1
clutureandmanagement       1
lunch                      1
culturandmanagement        1
brief                      1
opssandadmin               1
project-58                 1
project-42                 1
Name: project, Length: 144, dtype: int64

In [6]:
ci_df.user.unique()

array(['ned', 'robert', 'jaime', 'catelyn', 'cersei', 'daenerys', 'jorah',
       'viserys', 'jon', 'sansa', 'arya', 'robb', 'theon', 'bran',
       'joffrey', 'hound', 'tyrion', 'khal', 'littlefinger', 'davos',
       'samwell', 'stannis', 'melisandre', 'jeor', 'bronn', 'varys',
       'shae', 'margaery', 'tywin', 'talisa', 'ygritte', 'gendry',
       'tormund', 'brienne', nan, 'ramsay', 'gilly', 'daario',
       'missandei', 'ellaria', 'tommen'], dtype=object)

In [7]:
ci_df[ci_df['project']=='misc']

          user                       timestamp  hours project
7965      robb  2018-08-07 12:15:26.000233 UTC   1.00    misc
8217      robb         2018-08-03 00:00:00 UTC   4.00    misc
8242      robb            2 августа 2018 14:22   1.00    misc
8382      robb   2018-08-01 10:16:51.00001 UTC   0.50    misc
8445      robb  2018-07-31 12:52:43.000424 UTC   4.00    misc
8565      robb  2018-07-30 10:20:52.000009 UTC   2.00    misc
8794   joffrey         2018-07-26 00:00:00 UTC   1.00    misc
8800   joffrey         2018-07-26 00:00:00 UTC   0.25    misc
19826   tyrion  2017-07-28 02:15:31.518069 UTC   0.50    misc
19977   tommen  2017-07-21 10:53:12.388865 UTC   1.00    misc
20062   tommen   2017-07-19 10:12:33.40568 UTC   0.50    misc

In [8]:
def project_cleaner(proj):
    if proj[:2]=="op":
        return "opsandadmin"
    elif proj[:4]=="cult":
        return "cultureandmanagement"
    elif proj[:4]=="hirn":
        return "hiring"
    else:
        return proj

ci_df.project = ci_df.project.apply(lambda x: project_cleaner(x))

In [9]:
ci_df.project.unique()

array(['bizdev', 'cultureandmanagement', 'project-00', 'project-43',
       'project-47', 'project-30', 'opsandadmin', 'security', 'blogideas',
       'project-10', 'internal', 'project-51', 'transit', 'learning',
       'products', 'project-64', 'project-26', 'project-66', 'events',
       'project-25', 'project-32', 'project-31', 'finance', 'project-40',
       'engineering', 'project-09', 'project-65', 'project-28',
       'project-27', 'website', 'marketing', 'blog-ideas', 'hiring',
       'project-46', 'project-06', 'pm', 'project-07', 'legal',
       'project-33', 'strategy', 'project-05', 'project-62',
       'datastrategy', 'project-22', 'project-70', 'project-69',
       'project-04', 'project-38', 'internals', 'leave', 'recruitment',
       'clutureandmanagement', 'project-01', 'datastorytelling',
       'project-08', 'project-19', 'project-73', 'lunch', 'sqool',
       'project-20', 'onboarding', 'workshops', 'project-36', 'data',
       'machine-learning', 'weeklygoals', 'qgis', 'project-49', 'pandas',
       'project-59', 'brief', 'project-68', 'project-57', 'project-58',
       'project-16', 'media', 'new-office', 'd3js', 'workshop', 'misc',
       'random', 'project-13', 'project-29', 'design', 'machinelearning',
       'project-55', 'project-11', 'project-44', 'project-56',
       'project-41', 'dogood', 'project-02', 'braintooling', 'dataethics',
       'project-42', 'project-67', 'debugging', 'branding', 'project-34',
       'project-18', 'project-45', 'miscellaneous', 'project-39',
       'project-21', 'project-54', 'project-48', 'laptop', 'project-17',
       'project-24', 'project-23', 'blogpost', 'project-14', 'project-03',
       'traffic', 'airflow', 'project-72', 'project-37', 'breakout',
       'project-71', 'project-53', 'fatnesscheckin', 'project-52',
       'project-35', 'project-74', 'overthinking', 'project-61',
       'project-50', 'project-12', 'interns', 'project-63', 'friendship',
       'project-15', 'paperwork', 'project-60'], dtype=object)

In [10]:
ci_df.project.value_counts()

opsandadmin             2831
bizdev                  1784
cultureandmanagement    1278
learning                1179
project-00               946
project-10               672
website                  639
project-40               612
blogideas                567
project-43               526
project-68               485
project-64               484
project-25               467
project-65               465
project-20               456
hiring                   447
project-13               385
project-06               329
project-55               321
project-73               310
transit                  293
workshops                285
engineering              271
project-30               268
project-16               246
project-47               225
events                   219
project-51               215
project-27               206
project-32               200
                        ...
internals                  2
project-24                 2
pandas                     2
internal                   2
machine-learning           2
airflow                    2
fatnesscheckin             1
friendship                 1
project-15                 1
overthinking               1
weeklygoals                1
project-56                 1
miscellaneous              1
dogood                     1
project-60                 1
laptop                     1
dataethics                 1
project-21                 1
project-58                 1
brief                      1
project-61                 1
project-02                 1
clutureandmanagement       1
paperwork                  1
project-41                 1
project-39                 1
project-12                 1
lunch                      1
project-42                 1
traffic                    1
Name: project, Length: 134, dtype: int64

In [27]:
ci_df[ci_df['user']=='shae']

       user                       timestamp  hours               project
1837   shae         2018-10-26 00:00:00 UTC   10.0            project-43
1838   shae         2018-10-26 00:00:00 UTC   20.0            project-30
1839   shae         2018-10-26 00:00:00 UTC    2.0            project-10
1840   shae         2018-10-26 00:00:00 UTC    1.0            project-43
1841   shae             10/26/2018 12:00 AM    6.0            project-30
2818   shae         2018-10-15 00:00:00 UTC    0.5  cultureandmanagement
2819   shae         2018-10-15 00:00:00 UTC    3.0            project-30
2820   shae         2018-10-15 00:00:00 UTC    4.5            project-43
2821   shae         2018-10-15 00:00:00 UTC    3.0            project-10
2822   shae         2018-10-15 00:00:00 UTC   13.0            project-43
2826   shae         2018-10-15 00:00:00 UTC   15.0            project-30
2916   shae    2018-10-12 10:09:11.0001 UTC   30.0            project-43
2917   shae    2018-10-12 10:09:11.0001 UTC    8.0            project-10
3867   shae    2018-10-01 13:57:04.0001 UTC    3.0            project-30
3868   shae    2018-10-01 13:57:04.0001 UTC   21.0            project-43
3869   shae             10/01/2018 01:57 PM    7.0            project-10
3870   shae    2018-10-01 13:57:04.0001 UTC    0.5           opsandadmin
3871   shae    2018-10-01 13:57:04.0001 UTC    3.0            project-10
3872   shae    2018-10-01 13:57:04.0001 UTC    5.0            project-43
4099   shae    2018-09-27 15:56:31.0001 UTC    7.0            project-43
4100   shae    2018-09-27 15:56:31.0001 UTC    2.0            project-10
4101   shae             09/27/2018 03:56 PM   13.0            project-43
4102   shae    2018-09-27 15:56:31.0001 UTC   16.0            project-10
4930   shae         2018-09-19 00:00:00 UTC    2.0            project-00
4931   shae         2018-09-19 00:00:00 UTC    2.0                events
4932   shae         2018-09-19 00:00:00 UTC   10.0            project-10
4933   shae         2018-09-19 00:00:00 UTC    2.0            project-49
4934   shae         2018-09-19 00:00:00 UTC    2.0                events
4935   shae         2018-09-19 00:00:00 UTC    2.0            project-00
4936   shae         2018-09-19 00:00:00 UTC    2.0            project-10
...     ...                             ...    ...                   ...
19206  shae           18 августа 2017 13:22    1.0            project-55
19343  shae  2017-08-14 17:07:14.194127 UTC    1.0            project-55
19344  shae  2017-08-14 17:07:14.194127 UTC    8.0            project-55
19403  shae  2017-08-11 12:04:04.106593 UTC    1.0            project-55
19404  shae  2017-08-11 12:04:04.106593 UTC    7.0            project-55
19434  shae  2017-08-10 16:41:53.448707 UTC    1.0            project-55
19435  shae  2017-08-10 16:41:53.448707 UTC    2.0            project-55
19453  shae   2017-08-10 10:38:03.47311 UTC    4.0            project-55
19486  shae   2017-08-09 12:50:39.95179 UTC    3.0            project-55
19487  shae   2017-08-09 12:50:39.95179 UTC    4.0            project-55
19537  shae  2017-08-08 10:49:28.516305 UTC    8.0            project-55
19581  shae  2017-08-07 11:01:52.462575 UTC    1.0           opsandadmin
19582  shae  2017-08-07 11:01:52.462575 UTC    8.0            project-55
19610  shae            4 августа 2017 10:59    7.0            project-55
19611  shae  2017-08-04 10:59:38.719228 UTC    0.5            project-55
19650  shae    2017-08-03 13:53:48.8594 UTC    8.0            project-55
19706  shae  2017-08-02 10:44:31.959977 UTC    8.0            project-55
19711  shae             08/01/2017 02:38 PM    7.0            project-55
19712  shae  2017-08-01 14:38:22.032092 UTC    1.0            project-55
19765  shae  2017-07-31 10:36:46.415071 UTC    6.0            project-55
19788  shae             07/29/2017 02:39 PM    1.0            project-55
19789  shae  2017-07-29 14:39:05.097387 UTC    4.0            project-55
19843  shae  2017-07-27 10:23:17.605591 UTC    1.0            project-55
19844  shae  2017-07-27 10:23:17.605591 UTC    4.0              learning
19845  shae  2017-07-27 10:23:17.605591 UTC    2.0            project-55
19874  shae  2017-07-26 10:25:32.903056 UTC    1.0            project-55
19875  shae  2017-07-26 10:25:32.903056 UTC    2.0            project-55
19876  shae  2017-07-26 10:25:32.903056 UTC    1.0            project-55
19877  shae  2017-07-26 10:25:32.903056 UTC    2.0            project-46
19878  shae              26 июля 2017 10:25    1.0            project-55

[599 rows x 4 columns]

In [31]:
ci_df[ci_df['project']=='project-43']

            user                     timestamp  hours     project
5            ned       2019-09-26 00:00:00 UTC   1.00  project-43
17       catelyn  2018-11-26 14:47:36.0429 UTC   0.68  project-43
19       catelyn  2018-11-26 14:47:36.0429 UTC   1.53  project-43
33         jorah  2018-11-26 12:49:17.0405 UTC   1.50  project-43
75         theon  2018-11-26 09:00:55.0212 UTC   1.00  project-43
110       tyrion       2018-11-23 00:00:00 UTC   3.08  project-43
118        theon       2018-11-23 00:00:00 UTC   1.00  project-43
157        theon  2018-11-22 15:45:27.0511 UTC   3.00  project-43
224       tyrion       2018-11-22 00:00:00 UTC   3.00  project-43
245   melisandre       2018-11-22 00:00:00 UTC   3.45  project-43
246   melisandre       2018-11-22 00:00:00 UTC   4.00  project-43
249   melisandre       2018-11-22 00:00:00 UTC   2.00  project-43
262       tyrion  2018-11-21 14:25:19.0281 UTC   0.40  project-43
263        theon  2018-11-21 14:23:11.0277 UTC   5.50  project-43
298   melisandre       2018-11-21 00:00:00 UTC   0.78  project-43
328        theon  2018-11-20 15:50:29.0175 UTC   8.00  project-43
351        jorah  2018-11-20 10:39:49.0122 UTC   0.50  project-43
353        jorah  2018-11-20 10:39:49.0122 UTC   0.25  project-43
375      catelyn       2018-11-20 00:00:00 UTC   1.00  project-43
409       tyrion       2018-11-20 00:00:00 UTC   0.28  project-43
595        jorah  2018-11-16 10:38:39.0084 UTC   0.25  project-43
676      catelyn  2018-11-15 08:10:36.0719 UTC   0.25  project-43
689        jorah       2018-11-15 00:00:00 UTC   0.50  project-43
694      catelyn       2018-11-15 00:00:00 UTC   0.25  project-43
824      catelyn       2018-11-13 00:00:00 UTC   0.98  project-43
838        theon          12 ноября 2018 15:27   0.25  project-43
840        jorah           11/12/2018 12:41 PM   0.25  project-43
874      catelyn  2018-11-12 11:01:26.0102 UTC   0.23  project-43
878      catelyn  2018-11-12 11:01:26.0102 UTC   0.42  project-43
1001       theon  2018-11-09 10:50:17.1541 UTC   1.00  project-43
...          ...                           ...    ...         ...
6695     catelyn       2018-08-27 00:00:00 UTC   0.40  project-43
6719  melisandre       2018-08-25 00:00:00 UTC   0.78  project-43
6720  melisandre       2018-08-25 00:00:00 UTC   0.12  project-43
6732    daenerys  2018-08-24 13:16:00.0001 UTC   0.25  project-43
6763       jorah         24 августа 2018 10:32   0.50  project-43
6780       theon  2018-08-24 08:32:26.0001 UTC   4.50  project-43
6806  melisandre       2018-08-24 00:00:00 UTC   1.79  project-43
6813       jorah  2018-08-23 15:08:28.0001 UTC   1.50  project-43
6846     catelyn  2018-08-23 13:27:41.0001 UTC   0.15  project-43
6876  melisandre       2018-08-23 00:00:00 UTC   4.26  project-43
6889       bronn       2018-08-23 00:00:00 UTC   1.00  project-43
6892       theon       2018-08-23 00:00:00 UTC   1.00  project-43
6955       jorah  2018-08-22 10:39:28.0001 UTC   5.00  project-43
6973  melisandre         22 августа 2018 00:00   1.95  project-43
6984     catelyn       2018-08-22 00:00:00 UTC   0.45  project-43
7005     catelyn         22 августа 2018 00:00   0.05  project-43
7014       bronn           08/21/2018 02:44 PM   0.50  project-43
7015       bronn  2018-08-21 14:44:24.0001 UTC   1.00  project-43
7016       bronn           08/21/2018 02:44 PM   0.50  project-43
7017       bronn  2018-08-21 14:44:24.0001 UTC   2.50  project-43
7031       jorah       2018-08-21 00:00:00 UTC   1.50  project-43
7032       jorah       2018-08-21 00:00:00 UTC   6.00  project-43
7037     catelyn       2018-08-21 00:00:00 UTC   1.23  project-43
7038     catelyn       2018-08-21 00:00:00 UTC   4.73  project-43
7042  melisandre           08/21/2018 12:00 AM   2.60  project-43
7043  melisandre       2018-08-21 00:00:00 UTC   0.68  project-43
7063     catelyn  2018-08-20 13:52:26.0001 UTC   0.35  project-43
7140       jorah       2018-08-20 00:00:00 UTC   1.00  project-43
7151  melisandre       2018-08-20 00:00:00 UTC   4.73  project-43
7216     catelyn           08/17/2018 12:00 AM   0.55  project-43

[526 rows x 4 columns]

In [32]:
ci_df[ci_df['project']=='fatnesscheckin']

        user                       timestamp  hours         project
18189  davos  2017-09-22 11:09:54.000052 UTC    2.5  fatnesscheckin